import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-medium-image-zoom/dist/styles.css";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
